### PR TITLE
Add PolkaGate wallet extension

### PR DESCRIPTION
**Pull request by AMIRKHANEF**
Please add the PolkaGate wallet extension to the connection options.

The PolkaGate SVG icon has been added to the /icons folder.
{id, title, icon, url} have been added to the extensions/index.ts file.

Let's include the PolkaGate wallet extension as one of the available options for connecting.

Thank you!

### CODE REVIEW

**Comment by rossbulat** [comment]
Thanks for submitting @AMIRKHANEF!

When I have Polkadot JS installed alongside Polkagate I am getting the following errors upon a dashboard page load:

Screenshot 2023-04-14 at 11 43 24

Screenshot 2023-04-14 at 11 43 12

It looks like some code within Polkagate is acting on behalf of Polkadot JS. (maybe sourcing Polkadot JS accounts instead of its own).

Please let me know if I can assist in resolving. Let's iron out these issues before merging this PR.

**Comment by rossbulat** [comment]
Excellent, please ping me a message here when it has been deployed and we can continue this PR :)

**Comment by AMIRKHANEF** [comment]
> Excellent, please ping me a message here when it has been deployed and we can continue this PR :)

Thank you for the positive feedback. I will definitely let you know as soon as the changes have been deployed. Have a great day!

**Comment by rossbulat** [comment]
@AMIRKHANEF are you on Element? If so it would be great to connect on there. My handle is @ross:parity.io.

**Comment by AMIRKHANEF** [comment]
> @AMIRKHANEF are you on Element? If so it would be great to connect on there. My handle is `@ross:parity.io`.

Yes, I'm on Element.  I'll send you a message soon. Let's connect!

**Comment by AMIRKHANEF** [comment]
Hi @rossbulat,
I would like to inform you that the fix for the issue you mentioned has been included in the latest version of PolkaGate. Therefore, we believe that the pull request is now ready to merge. Thank you for your time and support!

**Comment by rossbulat** [comment]
Thanks @AMIRKHANEF! I have merged in #996. PolkaGate will be live in the next dashboard release later this month.

**Pull request closed without merging**
