### PR TITLE
Add Sekoya Labs to #Community

### PR DESCRIPTION
**Pull request by Sekoya-Labs**
Hi - Updating the community validator section to include Sekoya Labs. Thanks in advance!

Tom

### CODE REVIEW

**Comment by rossbulat** [comment]
Hi, thanks for submitting. Your SVG file is very large, in the interests of keeping the dashboard lean is there any leeway to decrease the file size?

**Comment by Sekoya-Labs** [comment]
@rossbulat I've greatly reduced the SVG image size. Let me know if this works. Thanks!

**Comment by Sekoya-Labs** [comment]
Pulled latest master

**Comment by rossbulat** [comment]
SVG looks awesome 👍

**Pull request merged**
