### PR TITLE
added LetzBake! as validator

### PR DESCRIPTION
**Pull request by amani1104**

### CODE REVIEW

**Comment by rossbulat** [comment]
Hi @amani1104, thanks for opening! Your logo is currently a png image wrapped in an SVG. Please could you provide a native SVG, preferrable 20kb or less in size.

**Comment by amani1104** [comment]
Done!

**Comment by amani1104** [comment]
Sorry, I forgot to add our website.

**Comment by rossbulat** [comment]
Sweet! Thanks, I'll minify and add via master.

**Comment by rossbulat** [comment]
Merged via master. Btw liking the website & branding!

**Comment by amani1104** [comment]
> Merged via master. Btw liking the website & branding!

Thank you!

**Pull request closed without merging**
