### PR TITLE
feat(i18n): french translation

### PR DESCRIPTION
**Pull request by roiLeo**
waiting for #255

### CODE REVIEW

**Comment by roiLeo** [comment]
> I am shortly going to merge another update, with help content translations. Would you be interested in translating these into French thereafter? 

I would be happy to handle French translation!

> There are upcoming change to the `pages` translations so the existing content in this PR will need to be slightly revised too.

Will update this PR with new changes.

**Comment by rossbulat** [comment]
This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by rossbulat** [comment]
Closing until we have a more solid translation strategy in place. Thank you for your contributions.

**Comment by roiLeo** [comment]
Oh no... what should I do on my side?

**Pull request closed without merging**
