### PR TITLE
add Stakenode validator to polkadot staking dashboard

### PR DESCRIPTION
**Pull request by jimmy-tudeski**

### CODE REVIEW

**Comment by rossbulat** [comment]
Hi @jimmy-tudeski , would it be possible to provide a native SVG, ideally no larger than 20kb? Purely for performance concerns as the dashboard should be able to handle a large number of these SVGs. We will be code splitting in the future but would still like to keep the icons light-weight. 
Please let me know if I can be of assistance in amending this.

**Comment by jimmy-tudeski** [comment]
Hi Ross,

thx for reaching out. Do You mind if I send it here attached if we are 
here already?

If You want me to do PR again by myself, please let me know, and thx a 
lot for Your assistance.

Have a Great evening!

Jimmy,

**Comment by jimmy-tudeski** [comment]
Hey Ross, Thx for reaching out. I decided to put a different logo. the file is updated, please let me know if it's ok no 

regards, jimmy

**Comment by jimmy-tudeski** [comment]
Hey Ross, Thx for reaching out. I decided to put a different logo. the file is updated, please let me know if it's ok no 

regards, jimmy

**Comment by rossbulat** [comment]
Added on master, thank you!

**Pull request closed without merging**
