### PR TITLE
Name change from LetzBake! to Blockshard due to rebranding

### PR DESCRIPTION
**Pull request by amani1104**
We recently changed our name and launched a new homepage.

### CODE REVIEW

**Comment by rossbulat** [comment]
Thanks for the update! SVGs are now React components so we can lazily load them in. Please can you rebase your branch & update the thumbnail file. Please let me know if any assistance is required.

**Comment by amani1104** [comment]
Can you please elaborate what you mean by that?

**Comment by rossbulat** [comment]
> Can you please elaborate what you mean by that?

Sure, the SVG component (`blockshard.svg`) now needs to be a React component of `Blockshard.tsx`, in the following format:

```
const Blockshard = () => (
  <svg>
    ...
  </svg>
);

export default Blockshard;
```

And in `config/validators/index.tsx`, you can simply provide a `Blockshard` string as the `thumbnail` property value.

**Comment by rossbulat** [comment]
I have made the changes myself at #791, thanks for the update!

**Pull request closed without merging**
