### PR TITLE
add PythagorasCapitalInvestment info

### PR DESCRIPTION
**Pull request by oeawFebe**
add PythagorasCapitalInvestment info

### CODE REVIEW

**Comment by rossbulat** [comment]
Hi @oeawFebe , thanks for submitting your info. Would it be possible to provide a native SVG image, ideally no larger than 20kb? Thanks.

**Comment by oeawFebe** [comment]
Thank you for the feedback. We made another SVG file which is 28kb, still slightly larger than 20kb. We would appreciate if you could accept it.

**Comment by rossbulat** [comment]
The issue now is that the image is still a PNG image wrapped in an SVG. What we really need is a native SVG file.

**Comment by oeawFebe** [comment]
This time I think it will work. Sorry for the confusion.

**Comment by rossbulat** [comment]
Added on master, thank you!

**Pull request closed without merging**
